name: Django CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Testen mit mehreren Python-Versionen

    steps:
    - uses: actions/checkout@v4  # Repository auschecken
      name: Checkout code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ifcopenshell  # Für IFC-Verarbeitung

    - name: Run Tests
      run: |
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: core.settings  # Pfad zu settings.py
